package guilherme.escarduca.MovieApi.Models;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.*;
import org.hibernate.validator.constraints.Range;
import org.springframework.hateoas.RepresentationModel;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.time.LocalDate;

@Entity
@Table(name ="movies")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @ToString
public class MovieModel extends RepresentationModel<MovieModel> {


/*    Title The title of the movie
    Date The launch date
    Rank Rating (0 to 10)
    Revenue The revenue generated by the movie*/
    @Id
    @Column(name = "id")
    private int id;
    @Column(name = "title")
    @Size(max = 50)
    @NotBlank(message = "Title cannot be blank")
    private String title;
    @Column(name = "launch_date")
    @JsonFormat(pattern = "yyyy-MM-dd")
    @NotNull(message = "LaunchDate cannot be null")
    private LocalDate launchDate;
    @Column(name = "rating")
    @Range(min = 0, max = 10, message = "Rating needs to be between 0 and 10")
    private int rating;
    @Column(name = "revenue")
    private double revenue;

}
